from setuptools import setup, find_packages

setup(
    name="raptool",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "rdkit",
        "rapidfuzz",
        "aiohttp",
        "tenacity",
        "pyarrow",
        "fastparquet",
        "seaborn",
        "matplotlib",
        "scikit-learn",
        "cython",
        "blosc2",
        "FuzzyTM",
        "PyYAML",
        "openpyxl",
        "bs4",
        "fastcluster",
        "pubchempy",
    ],
    python_requires=">=3.8",
    author="ToxIndex",
    author_email="info@toxindex.com",
    description="RAPtool - Rapid Analysis of Pharmaceutical Tools",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/toxindex/RAPtool",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
) 